---
- name: Converge
  hosts: all
  gather_facts: true
  vars:
    mariadb_data_dir: "{{ lookup('env', 'MARIADB_DATADIR') | default('/var/lib/mysql', true) }}"

  roles:
    - role: ansible-role-mariadb
