---
name: Default deployment

on:
  push:
    paths:
      - "files/**"
      - "handlers/**"
      - "molecule/default/**"
      - "tasks/**"
      - "templates/**"
      - "vars/**"
      - .github/workflows/composite-action/action.yml
      - .github/workflows/test_default.yml
      - requirements.txt
  schedule:
    - cron: "0 5 * * 2"

jobs:
  molecule-distrib-pkg:
    name: Default deployment
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro:
          - almalinux-9
          - almalinux-10
          - alpine-3.20
          - alpine-3.21
          - alpine-3.22
          - alpine-3.23
          - alpine-edge
          - centos-stream10
          - centos-stream9
          - debian-11
          - debian-12
          - debian-13
          - debian-sid
          - fedora-42
          - fedora-43
          - rockylinux-9
          - rockylinux-10
          - ubuntu-22.04
          - ubuntu-24.04
          - ubuntu-26.04
        include:
          - distro: debian-sid
            mariadb-datadir: /var/lib/mariadb
          - distro: ubuntu-26.04
            mariadb-datadir: /var/lib/mariadb

    steps:
      - uses: actions/checkout@v6
      - name: Setup environment
        uses: ./.github/workflows/composite-action
      - name: Run molecule
        run: |
          source .venv/bin/activate
          molecule test
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          MOLECULE_DISTRO: ${{ matrix.distro }}
          MARIADB_DATADIR: ${{ matrix.mariadb-datadir }}
